name: Node.js CI

on:
  push:
    branches: ["main", "routes"]
  pull_request:
    branches: ["main", "routes"]
  schedule:
    - cron: "0 12 * * 0-6"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Debug connection info
        run: |
          echo "Connecting to database on host: $AWS_SQL_HOST and port: $AWS_SQL_PORT"

      - name: Install dependencies
        run: npm ci
      - name: Run tests
        env:
          AWS_SQL_HOST: ${{ secrets.AWS_SQL_HOST }}
          AWS_SQL_PORT: ${{ secrets.AWS_SQL_PORT }}
          AWS_SQL_USER: ${{ secrets.AWS_SQL_USER }}
          AWS_SQL_PASS: ${{ secrets.AWS_SQL_PASS }}
          AWS_SQL_DB: ${{ secrets.AWS_SQL_DB }}
        run: npm run test
