# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main","routes" ]
  pull_request:
    branches: [ "main", "routes" ]
  schedule:
  - cron: '5 * * * 0-6'
  - cron: '10 * * * 0-6'
  - cron: '15 * * * 0-6'
  - cron: '20 * * * 0-6'
  - cron: '25 * * * 0-6'
  - cron: '30 * * * 0-6'
  - cron: '35 * * * 0-6'
  - cron: '40 * * * 0-6'
  - cron: '45 * * * 0-6'
  - cron: '50 * * * 0-6'
  - cron: '55 * * * 0-6'
  - cron: '0 * * * 0-6'
  
  

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run dev
    - run: npm run test
